version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce-postgres-staging
    environment:
      POSTGRES_DB: ecommerce_db_staging
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    networks:
      - ecommerce-staging-network

  redis:
    image: redis:7-alpine
    container_name: ecommerce-redis-staging
    ports:
      - "6380:6379"
    volumes:
      - redis_staging_data:/data
    networks:
      - ecommerce-staging-network

  app:
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
    container_name: ecommerce-app-staging
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: staging
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce_db_staging
      SPRING_DATASOURCE_USERNAME: ecommerce_user
      SPRING_DATASOURCE_PASSWORD: ecommerce_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_CACHE_TYPE: redis
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - ecommerce-staging-network

volumes:
  postgres_staging_data:
  redis_staging_data:

networks:
  ecommerce-staging-network:
    driver: bridge
